### ISSUE TITLE
UI - Salary Sheet

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#11]
Dashboard - Accounting - Salaries
URL:-  http://sultansecurity.azurewebsites.net/Management/Dashboard#/GuardSalaries

1.   In salary sheet please segregate payable salary to three columns (pay, overtime, replacement, net payable).

2.    Dashboard - Accounting - Salaries - Detail
URL:-   http://sultansecurity.azurewebsites.net/Management/Dashboard#/SalaryDetails/17

in detail of salary sheet there is Attendance (cash) column, there should be word "overtime " instead of "overtime hours"

**Comment by adilshehbaz** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet

![image](https://user-images.githubusercontent.com/30949546/29770664-8b29d560-8c09-11e7-86f3-dcc24e035364.png)
