### ISSUE TITLE
Change Filter option of entire software

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#14]
Filter option everywhere should be same like filter in scheduling

URL:- http://sultansecurity.azurewebsites.net/Management/Dashboard#/Scheduling

**Screenshot**
![image](https://user-images.githubusercontent.com/30949546/29312584-8ef5cd3c-81cf-11e7-800c-61bc686a62ed.png)

**Comment by adilshehbaz** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet

![image](https://user-images.githubusercontent.com/30949546/29770693-b055da1e-8c09-11e7-80d2-0261833a717e.png)

**Comment by adilshehbaz** [comment]
We have not Deployed Latest Version yet
