### ISSUE TITLE
Show Guard Code and Client Code 

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#15]
Please show Guard Code and Client Code everywhere it needed

**Comment by adilshehbaz** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet
**screenshot-1**
![image](https://user-images.githubusercontent.com/30949546/29770730-cff3c87c-8c09-11e7-8432-dd6c6f36c878.png)

**screenshot-2**
![image](https://user-images.githubusercontent.com/30949546/29770761-ec7b5028-8c09-11e7-8a8f-28575c8e597a.png)

**Comment by adilshehbaz** [comment]
We have not Deployed Latest Version yet
