### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#17]
LINK ISSUE 1 . =    http://sultansecurity.campusmanager.biz/Management/Dashboard#/dashboard
1. Go through the Dashboard. (Time, Guards on Duty etc.) ----   NOT WORKING **(RFR)**

LINK ISSUE 5 . =    http://sultansecurity.campusmanager.biz/Management/Dashboard#/Guards
5. Guard Code 0400028 (Location sahiwal – 1) invisible in Guard List.       NOT DONE **(RFR)**

LINK ISSUE 6. =    http://sultansecurity.campusmanager.biz/Management/Dashboard#/Attendance/History/

6. Attendance -> Assign Replacement -> no of replaced guards are not equal to absent guards.  **(RFR)**

LINK ISSUE 7. =     http://sultansecurity.campusmanager.biz/Management/Dashboard#/Attendance/History/

7. Attendance -> Assign Replacement ->show absent guard’s detail (Code & Name), show replaced guards detail (Code & Name), show client Code & Name, and show payment in cash in this window (because we pay replacement in cash).      NOT DONE **Fixed**

8. Client scheduling report as discussed, and export to Excel.         NOT DONE
9. Software generate list of clients when schedule that client gradually as discussed, and export to Excel.    NOT DONE

10. Client Scheduling -> show client code & name in heading (shown heading everywhere needed like Manage Guards, Clients, scheduling etc)  PARTIALLY DONE (heading of CLIENTS is not visible) **(Fixed)**

11. Client Feedback -> show full detail of feedback like (Date, Client Code, Client Name, Gun Condition, Guard Performance, Uniform Rating, Punctuality, Action), as discussed.  DONE BUT FEEDBACK NOT DELETING **(RFR)**

13. Filter option everywhere should be same like filter in scheduling.  DONE BUT FILTER NOT SEARCHING SAME LIKE SEARCHING IN SCHEDULING TAB **(Working Fine)**

14. Mark attendance -> add filter and sort option. NOT DONE AND THERE IS NOT SAVING MARKED ATTENDANCE VISIBLE **Already Fixed**

17. In salary sheet please segregate payable salary to three columns (pay , overtime / replacement, net payable).    NOT CHECKED DUE TO ATTENDANCE NOT SAVING , I will mark attendance than salary will be saved **Fixed**

**Comment by sajjadmgl** [comment]
related to point 1 (Dashboard) 
ye dashboard gaurds on duty ki stat hr different date py differnt dy raha hai, jesy 1st screenshot mie 300+ aur 2nd mie 162, jaha location select krty hai to Dashboard ko usi location ki stat show krni chahye, jesy Sahiwal-1 ho to just iski show kry r dusri locatin select kery to uski stat show kry.

**Comment by adilshehbaz** [comment]
LINK ISSUE 1 . = http://sultansecurity.campusmanager.biz/Management/Dashboard#/dashboard

Go through the Dashboard. (Time, Guards on Duty etc.)
**Fixed**

**Comment by adilshehbaz** [comment]
LINK ISSUE 6. = http://sultansecurity.campusmanager.biz/Management/Dashboard#/Attendance/History/

Attendance -> Assign Replacement -> no of replaced guards are not equal to absent guards. 
**Fixed**

**Comment by sajjadmgl** [comment]
LINK ISSUE 1 . = http://sultansecurity.campusmanager.biz/Management/Dashboard#/dashboard

Go through the Dashboard. (Time, Guards on Duty etc.)

not fixed.

just show the present guards in Guards on Duty table or segregate the Total Guards Scheduled and present guards 
and please offer Export to Excel to the Detail of Guards on Duty

**Comment by sajjadmgl** [comment]
LINK ISSUE 6. = http://sultansecurity.campusmanager.biz/Management/Dashboard#/Attendance/History/

Attendance -> Assign Replacement -> no of replaced guards are not equal to absent guards.

Not Fixed

i have select 11 absent guards in this shift and click on assign replacement button but there is only 8 guards visible instead of 11

and please show here a heading of which date and for which shift i am going to assign replacement

![image](https://user-images.githubusercontent.com/30949546/30589318-734ef424-9d53-11e7-98d6-2c86ab4f696e.png)

**Comment by adilshehbaz** [comment]
LINK ISSUE 5 . =    http://sultansecurity.campusmanager.biz/Management/Dashboard#/Guards
5. Guard Code 0400028 (Location sahiwal – 1) invisible in Guard List.       NOT DONE 
**Fixed**

**Comment by adilshehbaz** [comment]
Client Feedback -> show full detail of feedback like (Date, Client Code, Client Name, Gun Condition, Guard Performance, Uniform Rating, Punctuality, Action), as discussed. DONE BUT FEEDBACK NOT DELETING
**Fixed**

**Comment by adilshehbaz** [comment]
10. Client Scheduling -> show client code & name in heading (shown heading everywhere needed like Manage Guards, Clients, scheduling etc)  PARTIALLY DONE (heading of CLIENTS is not visible) **(Fixed)**

11. Client Feedback -> show full detail of feedback like (Date, Client Code, Client Name, Gun Condition, Guard Performance, Uniform Rating, Punctuality, Action), as discussed.  DONE BUT FEEDBACK NOT DELETING **(RFR)**

13. Filter option everywhere should be same like filter in scheduling.  DONE BUT FILTER NOT SEARCHING SAME LIKE SEARCHING IN SCHEDULING TAB **(Working Fine)**

14. Mark attendance -> add filter and sort option. NOT DONE AND THERE IS NOT SAVING MARKED ATTENDANCE VISIBLE **Already Fixed**

**Comment by adilshehbaz** [comment]
7. Attendance -> Assign Replacement ->show absent guard’s detail (Code & Name), show replaced guards detail (Code & Name), show client Code & Name, and show payment in cash in this window (because we pay replacement in cash).      NOT DONE **Fixed**

**Comment by adilshehbaz** [comment]
17. In salary sheet please segregate payable salary to three columns (pay , overtime / replacement, net payable).    NOT CHECKED DUE TO ATTENDANCE NOT SAVING , I will mark attendance than salary will be saved **Fixed**

**Comment by sajjadmgl** [comment]
new feedback is uploaded as discussed
