### ISSUE TITLE
UI - Dashboard

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#4]
**TOP PRIORITY**
URL :-      http://sultansecurity.azurewebsites.net/Management/Dashboard#/dashboard

1.	Go through the Dashboard. (Time, Guards on Duty etc.)
2.      Show detail of present guards for previous day (because today we will mark attendance for yesterday)
3.      Show a table for Client detail (how many guards are required by how many clients)
4.      Show a table for active clients detail
5.      Please Add the Row (Total) below every table visible on Dashboard.

**Comment by nawabanjum** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet

![image](https://user-images.githubusercontent.com/30949546/29770522-04d0bf7e-8c09-11e7-82ba-9cf83bd640ac.png)
