### ISSUE TITLE
UI - Assign Replacements

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#7]
Dashboard - Guards - Attendance - Assign Replacements
URL;- http://sultansecurity.azurewebsites.net/Management/Dashboard#/Attendance/AutoAssignReplacements/605

1.    No of replaced guards is not equal to absent guards. (If Absents are 10, replace guards show less then 10)
2.   Show absent guard’s detail (Code & Name), show replaced guards detail (Code & Name), show client Code & Name, and add a column to enter payment in cash in this window (because we pay replacement in cash).

**Comment by adilshehbaz** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet

![image](https://user-images.githubusercontent.com/30949546/29770589-3df41602-8c09-11e7-9ca5-4a98550456d6.png)
