### ISSUE TITLE
UI - Clients Feedback

### ISSUE THREAD

**Issue by sajjadmgl** [serviceproviderpk/sultansec#9]
Dashboard - Clients - Feedbacks
URL:-   http://sultansecurity.azurewebsites.net/Management/Dashboard#/ClientFeedback

Show full detail of feedback like (Date, Client Code, Client Name, Gun Condition, Guard Performance, Uniform Rating, Punctuality, Action), as discussed.

**Comment by adilshehbaz** [comment]
**Fixed**

**Comment by sajjadmgl** [comment]
not fixed yet

![image](https://user-images.githubusercontent.com/30949546/29770641-69c071fe-8c09-11e7-9ff2-6c040560fc28.png)
